### PR TITLE
fix(prefixStorage): prefix `getItems` and `setItems`

### LINKED ISSUE #396: `getItems` does not work with `prefixStorage`
### Environment

1.10.1

### Reproduction

https://stackblitz.com/edit/stackblitz-starters-rrstqp?file=index.js

### Describe the bug

Working

```ts
useStorage().getItems(['namespace:key'])
```

Not Working

```ts
prefixStorage(useStorage(), 'namespace').getItems(['key'])
useStorage('namespace').getItems(['key'])

// { key: "key", value: null }
```

It seems to switch back to the default driver (`memory`). I'm guessing this is because the mount is being discovered from the input key, without the base being applied first.

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by jlucaso1**
Enhance the `prefixStorage` function to correctly handle `getItems` and `setItems` by applying the prefix to keys. This resolves the issue where `getItems` was returning null for prefixed keys. Additional tests ensure that both `getItems` and `setItems` function as expected with prefixed keys.

Fixes #396

### CODE REVIEW

File: src/utils.ts [hunk 1]
```diff
@@ -44,6 +44,44 @@ export function prefixStorage<T extends StorageValue>(
       // Remove Prefix
       .then((keys) => keys.map((key) => key.slice(base.length)));
 
+  if (typeof storage.getItems === "function") {
+    nsStorage.getItems = <U extends T>(
+      items: (string | { key: string; options?: any })[],
+      commonOptions?: any
```
Comment (43081j) [inline src/utils.ts:50]: both `options` and `commonOptions` are `TransactionOptions`. so you may as well use the real type here instead of `any`

File: src/utils.ts [hunk 2]
```diff
@@ -44,6 +44,44 @@ export function prefixStorage<T extends StorageValue>(
...
+          value: entry.value,
+        }))
+      );
+    };
+  }
+
+  if (typeof storage.setItems === "function") {
+    nsStorage.setItems = <U extends T>(
+      items: { key: string; value: U; options?: any }[],
+      commonOptions?: any
```
Comment (43081j) [inline src/utils.ts:74]: again these too can be `TransactionOptions`

File: test/storage.test.ts [hunk 3]
```diff
@@ -249,4 +249,43 @@ describe("Regression", () => {
       await storage.clear();
     }
   });
+
+  it("prefixStorage getItems returns null (issue #396)", async () => {
```
Comment (43081j) [inline test/storage.test.ts:253]: is this test description wrong/old? 👀 

since it seems we're testing that `getItems` returns values and non-prefixed keys

**Review by 43081j — COMMENTED** [review]
looks good to me 👍 

will leave pooya to approve/merge

File: test/storage.test.ts (hunk 3 above)
Comment (jlucaso1) [reply test/storage.test.ts:253]: It's old. I used this test to replicate the bug

**Review by pi0 — APPROVED** [review]
Thanks ❤️
